// Generated by gencpp from file robot_controllers_msgs/QueryControllerStatesFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROLLERS_MSGS_MESSAGE_QUERYCONTROLLERSTATESFEEDBACK_H
#define ROBOT_CONTROLLERS_MSGS_MESSAGE_QUERYCONTROLLERSTATESFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_controllers_msgs/ControllerState.h>

namespace robot_controllers_msgs
{
template <class ContainerAllocator>
struct QueryControllerStatesFeedback_
{
  typedef QueryControllerStatesFeedback_<ContainerAllocator> Type;

  QueryControllerStatesFeedback_()
    : state_diff()  {
    }
  QueryControllerStatesFeedback_(const ContainerAllocator& _alloc)
    : state_diff(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_controllers_msgs::ControllerState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_controllers_msgs::ControllerState_<ContainerAllocator> >::other >  _state_diff_type;
  _state_diff_type state_diff;





  typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct QueryControllerStatesFeedback_

typedef ::robot_controllers_msgs::QueryControllerStatesFeedback_<std::allocator<void> > QueryControllerStatesFeedback;

typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesFeedback > QueryControllerStatesFeedbackPtr;
typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesFeedback const> QueryControllerStatesFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator1> & lhs, const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.state_diff == rhs.state_diff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator1> & lhs, const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_controllers_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "884ebbcebb33b2855209539dadfa0dc6";
  }

  static const char* value(const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x884ebbcebb33b285ULL;
  static const uint64_t static_value2 = 0x5209539dadfa0dc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_controllers_msgs/QueryControllerStatesFeedback";
  }

  static const char* value(const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Action feedback:\n"
"# Status changes in controllers as they are started/stopped\n"
"ControllerState[] state_diff\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_controllers_msgs/ControllerState\n"
"# Valid states:\n"
"\n"
"uint8 STOPPED = 0\n"
"uint8 RUNNING = 1\n"
"uint8 ERROR = 2\n"
"\n"
"string name\n"
"string type\n"
"uint8 state\n"
;
  }

  static const char* value(const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_diff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryControllerStatesFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_controllers_msgs::QueryControllerStatesFeedback_<ContainerAllocator>& v)
  {
    s << indent << "state_diff[]" << std::endl;
    for (size_t i = 0; i < v.state_diff.size(); ++i)
    {
      s << indent << "  state_diff[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_controllers_msgs::ControllerState_<ContainerAllocator> >::stream(s, indent + "    ", v.state_diff[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROLLERS_MSGS_MESSAGE_QUERYCONTROLLERSTATESFEEDBACK_H
